from tkinter import *
ablak=Tk()
mezo1=Entry(ablak)
mezo1.grid(row=0, column=2)
mezo1felirat=Label(ablak, text="Első mező:")
mezo1felirat.grid(row=0, column=1)
mezo2=Entry(ablak)
mezo2.grid(row=1, column=2)
mezo2felirat=Label(ablak, text="Második mező:")
mezo2felirat.grid(row=1, column=1)
mezo3=Entry(ablak)
mezo3.grid(row=2, column=2)
mezo3felirat=Label(ablak, text="Harmadik mező: ")
mezo3felirat.grid(row=2, column=1)
ablak.mainloop()